// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jOyU6KdYHjF2yANu7Bre_5yTU88FNCc',
    appId: '1:126070463509:web:a406a1f125aee9cd67821c',
    messagingSenderId: '126070463509',
    projectId: 'flutterapp-18b71',
    authDomain: 'flutterapp-18b71.firebaseapp.com',
    storageBucket: 'flutterapp-18b71.appspot.com',
    measurementId: 'G-HK3GWW3VWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2gSxMsZw_rFiYxq9Y3fj-8AJS90zahY',
    appId: '1:126070463509:android:a7d3c3e97fb3478567821c',
    messagingSenderId: '126070463509',
    projectId: 'flutterapp-18b71',
    storageBucket: 'flutterapp-18b71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALpKRcH2LBsuZHWJMwGpCHMI2mBx4u978',
    appId: '1:126070463509:ios:c583c490646cd63067821c',
    messagingSenderId: '126070463509',
    projectId: 'flutterapp-18b71',
    storageBucket: 'flutterapp-18b71.appspot.com',
    iosBundleId: 'com.example.pertemuan8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALpKRcH2LBsuZHWJMwGpCHMI2mBx4u978',
    appId: '1:126070463509:ios:c583c490646cd63067821c',
    messagingSenderId: '126070463509',
    projectId: 'flutterapp-18b71',
    storageBucket: 'flutterapp-18b71.appspot.com',
    iosBundleId: 'com.example.pertemuan8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6jOyU6KdYHjF2yANu7Bre_5yTU88FNCc',
    appId: '1:126070463509:web:efeaae89c2e92d8667821c',
    messagingSenderId: '126070463509',
    projectId: 'flutterapp-18b71',
    authDomain: 'flutterapp-18b71.firebaseapp.com',
    storageBucket: 'flutterapp-18b71.appspot.com',
    measurementId: 'G-LXDE231JQH',
  );

}